---
title: "About this site"
description: |
  Some additional details about the website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The is a course website for ACC 8143 Accounting Data Analytics. This course is derived from a Deloitte Data Analytics course made by the [University of Illinois.](https://giesbusiness.illinois.edu/experience/academies-centers/the-university-of-illinois-deloitte-foundation-center-for-business-analytics/courses)

Students will use R statistical software for ETL (extraction, transformation, and loading data). Specifically, R and RStudio (GUI for R) will be used in conjunction with Tidyverse R packages for advanced manipulation and visualizations. Students will learn to use Git and GitHub. Git and GitHub are extensively used for data analytics in practice. GitHub will show the students the importance of version control and the value of coding with care. Students will also learn Markdown which is a framework for presenting interactive reports, dashboards, and creating websites. Students will use RStudio, GitHub, Markdown, and Distill r package to make a professional website for showcasing their work in the class. This will help students learn the value of presenting information in a business analytics context and presenting their own work for others to see. Using Rstudio the students will learn how popular machine learning algorithms work, the difference between parametric and nonparametric algorithms, supervised and unsupervised algorithms, the bias-variance trade-off, and overfitting and underfitting algorithms with hands on examples in business contexts.
