---
title: "Logic or the lack thereof"
description: |
  Logic fallacies are a tool for the foolish and recognizing them is your only defense.
author: "Professor Hunt"
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
---

# Logical Fallacies

Logical fallacies are dangerous because people can use them unintentionally or worse intentionally because their argument is poor. Critical thinking and logic are inseparable, but I would argue that one cannot think critically without understanding logic.

This page lists common logical fallacies and gives examples. I plan on adding to this list until it is complete.

## The List

```{=html}
<style>
.collapsible {
  background-color: white;
  color: #5D1725;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 18px;
  font-weight: bold;
}

.active, .collapsible:hover {
  background-color: #555;
}

.content {
  padding: 0 18px;
  display: none;
  overflow: hidden;
  background-color: white;
}
</style>

<button type="button" class="collapsible">argumentum ad speculum</button>
<div class="content">
  <p>
```
### argumentum ad speculum

#### Counterfactual fallacy

Occurs when someone states a fact, then states something would be true if the stated fact were not true without other evidence.

##### Common layout

-   A causes B

-   A is true

-   Therefore, B is true

**Fallacy**: Therefore, if counterfactual A was false, then counterfactual B would be false

##### Worse

-   A is true

-   B is true

**Fallacy**: Therefore, if counterfactual A was false, then counterfactual B would be false

**Counterfactual**: a conditional statement the first clause of which expresses something contrary to fact, as "If I had known."

**Example**: My cousin died of covid, but he would not have died if he were vaccinated.

-   Cousin died

-   Vaccines reduce the chance of death

**Fallacy**: My cousin would have lived, if he had taken the vaccine.

[**This is literally unknowable**]{.ul}

```{=html}
</p>
</div>
```
```{=html}
<button type="button" class="collapsible">Straw Man</button>
<div class="content">
  <p>
```
### Straw Man

Occurs when someone argues against a made up argument, while completely side stepping the original argument.

##### Common layout

-   Person 1 asserts A

-   Person 2 argues an extreme version of A or something tangentially related B, but never addresses A.

**Example**:

-   Wife: I'd rather have a dog than a cat.

-   Husband: Why do you hate cats?

**Fallacy:** The wife never said that she hated cats, only that she preferred dogs. The husband either assumed or pretended that her argument was against cats instead of for dogs. Now the wife must argue that she doesn't hate cats --- which completely changes the course of the discussion.

**Other forms**:

-   Quoting an opponent's words out of context

-   Oversimplifying an opponent's argument, then attacking this oversimplified version.

-   Exaggerating (sometimes grossly exaggerating) an opponent's argument, then attacking this exaggerated version.

```{=html}
</p>
</div>
```
```{=html}
<button type="button" class="collapsible">argumentum ad hominem</button>
<div class="content">
  <p>
```
### Ad hominem

Ad hominem, short for argumentum ad hominem, is a logical fallacy that is based on personal and irrelevant attacks against the source of an argument, instead of addressing the argument itself.

The attacker takes aim at their opponent's supposed failings, that are unrelated to the issue at hand, rather than focusing on the validity of the argument or position they support.

There are five main types of ad hominems: *abusive*, circumstantial, *tu quoque*, *guilt by association*, and *poisoning the well*.

#### Abusive

*Ad hominem abusive* is probably the most frequently occurring type. It occurs when someone makes an abusive attack towards someone by criticizing their attributes such as character, background, morals, physical appearance, or hobbies. In other words, it's an attempt to discredit an argument by insulting the arguer.

It is also known as "name-calling" and "damning the source".

Its logical form goes as:

-   Person A makes argument X.

-   Person A is an idiot.

-   Therefore, argument X is false.

    Example:

    -   Prof. Hunt: Masks are ineffective.

    -   ignorant person: You are an accounting professor, not a doctor.

#### Circumstantial

*Circumstantial ad hominem*, also known as "appeal to motive", arises when someone says that since a certain claim must be predisposed by the arguer's personal circumstances, it is therefore invalid.

This is logically fallacious specifically because it asserts that an argument *must* be false if there is such a connection between a person's circumstances and their claim that could possibly affect their decision-making. In reality, however, it doesn't disprove the logic or validity of the claim; a car salesman may really believe that the car he is selling is an excellent vehicle.

As such, its logical form is:

-   Person 1 makes an argument X.

-   Person 1 has a personal interest in X to be true.

-   Therefore, X is false.

However, note that if there is strong evidence for a conflict of interest and enough reasons to believe that the individual's position is indeed biased, it is reasonable to call them out on it.

Example: Professor Hunt does not want to wear a mask so his assertion is false.

#### Tu Quoque

Also called the *appeal to hypocrisy*, *tu quoque* (Latin for "you too") is based on the claim that a person's argument must be invalid because their past actions or words are not consistent with it.

In essence, rather than trying to refute the logic or evidence the person is using, one responds by pointing out that he or she has acted in the same manner themselves.

It's considered to be a flawed line of reasoning because, even though it may show the opponent's hypocrisy, it doesn't really address the actual substance of an argument.

The logical form a *tu quoque* is:

-   Person 1 makes an argument X.

-   Person 2 points out that X is also true about person 1.

-   Therefore, X is false.

Example: Professor Hunt is current wearing a mask so his assertion must be false.

#### Guilt by Association

*Guilt by association* is a type of *ad hominem* fallacy in which someone is discredited due to their supposed association with something negative; since the characteristics of something negative, such as a bad person or an evil idea, and the characteristics of the person that it's associated with are said to be the same, the person is therefore viewed as "guilty" too.

The typical form for this argument is:

-   Person 1 supports position X.

-   Person 2, who is evil, also supports X.

-   Therefore, person 1 is evil too.

When this type of fallacious connection is made in a positive context, it's called *honor by association*. The reasoning behind it is the same, only the person or a group is associated with something that is seen as positive.

Example: Lady Hunt also believes masks are ineffective and she is crazy. Man Hunt must be crazy too.

#### Poisoning the Well

*Poisoning the well* is a fallacy that arises when negative information about someone is presented preemptively in order to discredit or ridicule following claims made by that person.

It is also known as *smear tactic*; rather than having to counter a claim in legitimate ways, one resorts to smearing their opponent's reputation and thus making their words less credible.

Example: Professor Hunt is a conspiracy theorist so you should not believe anything he says.

```{=html}
</p>
</div>
```
```{=html}
<button type="button" class="collapsible">Ignoratio elenchi</button>
<div class="content">
  <p>
```
### Red Herring

##### The latin means "Irrelevant Conclusion"

**Description:** Attempting to redirect the argument to another issue to which the person doing the redirecting can better respond. The *red herring* is a deliberate diversion of attention with the intention of trying to abandon the original argument.

**Logical Form:**

Argument A is presented by person 1.

Person 2 introduces argument B.

Argument A is abandoned.

**Example:**

Person 1: The vaccine is unnecessary for children.

Person 2: We have to do what is best for society.

Argument shifts to society and discussion of children is abandoned.

Note: The red herring fallacy differs from the straw man fallacy in that the opponent's argument or position is not misrepresented - the opponent's argument is simply abandoned.

```{=html}
</p>
</div>

<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}
</script>
```
fin
